<div class="header-wrap">
    <div class="header-nav-bar">
        <div class="h-n-b-logo fl">
            <img src="../images/icon/logo.jpg" alt="">
        </div>
        <div class="header-memu fl">
            <ul>
                <li><a href="index.html"><span>主页</span></a></li>
                <li><a href="orderlist.html"><span>我的订单</span></a></li>
                <li><a href="wode.html"><span>个人中心</span></a></li>
                <li><a href="zxzx.html"><span>资讯中心</span></a></li>
                <li><a href="login.html"><span>登录/注册</span></a></li>

            </ul>
        </div>
        <div class="gwc-nav fr">
            <a href="cat.html">
                <i class="iconfont icon-gouwuche"></i>
                <span>1</span>
            </a>
        </div>
    </div>
</div>