<div class="left-side fl">
           <ul>
               <li><span>全部功能</span></li>
               <li><a href="wode.html"><span id="@@geren">个人中心</span></a></li>
               <li><a href="dlgl.html"><span id="@@daili">代理管理</span></a></li>
               <li><a href="orderlist.html"><span id="@@dingdan">我的订单</span></a></li>
               <li><a href="address.html"><span id="@@dizhi">地址管理</span></a></li>
               <li><a href="mendian.html"><span id="@@mendian">门店地址</span></a></li>
               <li><a href="tuiguang.html"><span id="@@tuiguang">我的推广</span></a></li>
               <li><a href="tie.html"><span id="@@tixian">提现管理</span></a></li>
               <li><a href="fanyong.html"><span id="@@yongjin">佣金返现</span></a></li>
               <li><a href="txjl.html"><span id="@@txjl">提现记录</span></a></li>
               <li><a href="czjl.html"><span id="@@czjl">充值记录</span></a></li>
           </ul>
        </div>